### ISSUE TITLE
Result not getting for this xpath "Quote/Coverage[2]/Name"

### ISSUE THREAD

**Issue by lmanideepkumar** [nicolay-anykienko/AnyTreeXPath#1]
I am using XPath like "Quote/Coverage[2]/Name" to get the Name Value. But it returns count as zero.

Please find the below JSON files. and let me know how to use this type of XPath in this project.

JSON:
{
  "Quote": {
    "-xmlns": "http://www.valuemomentum.com/BizDynamics",
    "QuoteID": "1325",
    "Coverage": [
      {
        "Id": "234",
        "Name": "GeneralLiabilityMedPayCoverage",
        "Premium": "125.00",
        "CurrentPremium": "125.00 ",
        "RevisedPremium": "125.00",
        "CoverageAttributes": {
          "CoverageAttribute": {
            "Name": "Limit",
            "Value": "10000"
          }
        }
      },
      {
        "Id": "234",
        "Name": "GeneralLiabilityDamageToPremisesRentedToYouCoverage",
        "Premium": "125.00",
        "CurrentPremium": "125.00 ",
        "RevisedPremium": "125.00",
        "CoverageAttributes": {
          "CoverageAttribute": {
            "Name": "Limit",
            "Value": "6000"
          }
        }
      }
    ]
  }
}

XML:

<Quote xmlns="http://www.valuemomentum.com/BizDynamics" >
  <QuoteID>1325</QuoteID>
   <Coverage>
          <Id>234</Id>
          <Name>GeneralLiabilityMedPayCoverage</Name>
          <Premium>125.00</Premium>
          <CurrentPremium>125.00 </CurrentPremium>
          <RevisedPremium>125.00</RevisedPremium>
          <CoverageAttributes>
            <CoverageAttribute>
              <Name>Limit</Name>
              <Value>10000</Value>
            </CoverageAttribute>
          </CoverageAttributes>
    </Coverage>
   <Coverage>
          <Id>234</Id>
          <Name>GeneralLiabilityDamageToPremisesRentedToYouCoverage</Name>
          <Premium>125.00</Premium>
          <CurrentPremium>125.00 </CurrentPremium>
          <RevisedPremium>125.00</RevisedPremium>
          <CoverageAttributes>
            <CoverageAttribute>
              <Name>Limit</Name>
              <Value>6000</Value>
            </CoverageAttribute>
          </CoverageAttributes>
    </Coverage>   
 </Quote>

With Regards,
Manideep Lakkakula.

**Comment by nicolas-2008** [comment]
Hello, Manideep

Thanks for interesting in my project.

My implementation of XPath for JSON treats array items as inner objects of parent object, i.e. example JSON object you provided consists of single object named 'Coverage' with two unnamed objects inside.

You may achieve the result by adjusting your xpath query in the following way:
**_"Quote/Coverage/*[2]/Name"_**
or 
**_"Quote/Coverage/*[name()=''][2]/Name"_**, if you want to query only _unnamed_ objects inside 'Coverage' object.

Best regards,
Nicolay Anykienko

**Comment by lmanideepkumar** [comment]
Thank you so much for reply.

I have one more query, I have a xpath like ,,"Quote/Coverage[Name='GeneralLiabilityMedPayCoverage']/Value" ..can you give me how to use this xpath by using your code snippet.

Thank you for your endless support.

With regards,
Manideep lakkakula.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nicolas-2008** [comment]
To simplify such kinds of queries I decided to extend the functionality to allow usage of json property nodes with simple values as XPath attributes.
Please update the repository, and after that you may use the following query to achieve the result:
**_"Quote/Coverage/*[@Name='GeneralLiabilityMedPayCoverage']//Value"_**

Best regards,
Nicolay Anykienko
